chore(ci): adding a deconnexion test
Signed-off-by: Raphael Defosseux <raphael.defosseux@eurecom.fr>

diff --git a/ci-scripts/Jenkinsfile-GitLab-COTS-UE-Test b/ci-scripts/Jenkinsfile-GitLab-COTS-UE-Test
--- a/ci-scripts/Jenkinsfile-GitLab-COTS-UE-Test
+++ b/ci-scripts/Jenkinsfile-GitLab-COTS-UE-Test
@@ -222,13 +222,6 @@ pipeline {
           sh "docker image inspect --format='Size = {{.Size}} bytes' ${ranFullImage} >> archives/oai-gnb-image-info.log"
           sh "echo 'OC Pushed Tag is N/A' >> archives/oai-gnb-image-info.log"
           stash allowEmpty: true, includes: 'archives/oai-gnb-image-info.log', name: 'gNB_image'
-          // Check for entrypoint content (until 2023.w22)
-          sh "docker create --name test-entrypoint ${ranFullImage}"
-          sh "docker cp test-entrypoint:/opt/oai-gnb/bin/entrypoint.sh gnb-entrypoint.sh"
-          sh "docker rm -f test-entrypoint"
-          entryContent = sh returnStdout: true, script: "cat gnb-entrypoint.sh"
-          mountedFileAsMountedDotConf = entryContent.contains('create sed expressions for substituting each occurrence')
-          sh "rm -f gnb-entrypoint.sh"
           // Adding capture on SCTP and L2 port 9999
           sh "sudo rm -f /tmp/oai-gnb-l2-trace.pcap /tmp/oai-gnb-l2-trace.logs"
           sh 'nohup sudo tshark -i any -f "sctp or udp port 9999" -w /tmp/oai-gnb-l2-trace.pcap > /tmp/oai-gnb-l2-trace.logs 2>&1 &'
@@ -239,9 +232,6 @@ pipeline {
             sh "sudo uhd_find_devices > /dev/null 2>&1 || true"
             sleep 5
             sh "sed -i -e 's@image: oaisoftwarealliance/oai-gnb:develop@image: ${ranFullImage}@' docker-compose.yml"
-            if (mountedFileAsMountedDotConf) {
-              sh "sed -i -e 's@/opt/oai-gnb/etc/gnb.conf@/opt/oai-gnb/etc/mounted.conf@' docker-compose.yml"
-            }
             sh "docker-compose up -d"
             deployedGNB = true
             gNBStatus = checkStatusOnGNB()
@@ -328,6 +318,91 @@ pipeline {
             sh 'cp -f /tmp/test-*.log /tmp/test-*.png archives || true'
             sh 'sudo rm -f /tmp/test-*.log /tmp/test-*.png || true'
             stash allowEmpty: true, includes: 'archives/*.*', name: 'ue_logs'
+          }
+        }
+      }
+    }
+    stage ('Deconnexion Test - Attach UE') {
+      agent { label ue_ctl_server }
+      steps {
+        lock(ue_ctl_resource) {
+          script {
+            echo '\u2705 \u001B[32mTesting the Deconnexion - Attach UE again\u001B[0m'
+            sh 'mkdir -p archives/deconnexion-test'
+            dir ('ci-scripts/cots-ue-mbim-scripts') {
+              // I don't want that stage to fail.
+              // It's easier then to un-deploy gNB.
+              try {
+                sh 'sudo bash -c "set -o pipefail && ./start.sh 2>&1 | tee /tmp/test-start2.log"'
+              } catch (Exception e) {
+                echo "Test-Start #2 seems to have failed!"
+              }
+            }
+            sh 'sudo chmod 666 /tmp/test-start2.log || true'
+            sh 'cp -f /tmp/test-start2.log archives/deconnexion-test || true'
+            sh 'sudo rm -f /tmp/test-start2.log || true'
+            stash allowEmpty: true, includes: 'archives/deconnexion-test/*.*', name: 'ue_logs_start2'
+          }
+        }
+      }
+    }
+    stage ('Deconnexion Test - Restart gNB') {
+      agent { label gnb_server }
+      steps {
+        script {
+          echo '\u2705 \u001B[32mTesting the Deconnexion - Restart gNB\u001B[0m'
+          sh 'mkdir -p archives/first_stop'
+          if (deployedGNB) {
+            sh "sudo pkill tshark || true"
+            sleep 2
+            sh "sudo chmod 666 /tmp/oai-gnb-l2-trace.* || true"
+            dir ('ci-scripts/docker-compose/gnb-ci-testbed') {
+              ranFullImage = fixFullRanImageTag(params.FULL_RAN_TAG)
+              sh "sed -i -e 's@image: oaisoftwarealliance/oai-gnb:develop@image: ${ranFullImage}@' docker-compose.yml"
+              // Stop the gNB.
+              sh "docker-compose stop -t 3 || true"
+              sleep 2
+              sh "docker logs sa-b210-gnb > ../../../archives/first_stop/oai-gnb.logs 2>&1 || true"
+              sh "cp /tmp/oai-gnb-l2-trace.* ../../../archives/first_stop || true"
+              sh "sudo rm -f /tmp/oai-gnb-l2-trace.*"
+
+              // Adding capture on SCTP and L2 port 9999
+              sh "sudo rm -f /tmp/oai-gnb-l2-trace.pcap /tmp/oai-gnb-l2-trace.logs"
+              sh 'nohup sudo tshark -i any -f "sctp or udp port 9999" -w /tmp/oai-gnb-l2-trace.pcap > /tmp/oai-gnb-l2-trace.logs 2>&1 &'
+              sleep 2
+
+              // Restart the gNB again
+              sh "docker-compose restart || true"
+              checkStatusOnGNB()
+            }
+            stash allowEmpty: true, includes: 'archives/first_stop/*.*', name: 'gNB_logs_after_first_stop'
+          }
+        }
+      }
+    }
+    stage ('Deconnexion Test - Check Re-Attachement of UE') {
+      agent { label ue_ctl_server }
+      steps {
+        lock(ue_ctl_resource) {
+          script {
+            echo '\u2705 \u001B[32mTesting the Deconnexion - Check Re-Attachement of UE\u001B[0m'
+            sh 'mkdir -p archives/deconnexion-test'
+            dir ('ci-scripts/cots-ue-mbim-scripts') {
+              sleep 60
+              // I don't want that stage to fail.
+              // It's easier then to un-deploy gNB.
+              sh 'ping -I wwan0 -c 4 8.8.8.8 2>&1 | tee ../../archives/deconnexion-test/ping_post_deconnexion.log'
+              sh 'ping -I wwan0.1 -c 4 8.8.8.8 2>&1 | tee -a ../../archives/deconnexion-test/ping_post_deconnexion.log'
+              try {
+                sh 'sudo bash -c "set -o pipefail && ./stop.sh 2>&1 | tee /tmp/test-stop2.log"'
+              } catch (Exception e) {
+                echo "Test-Stop #2 seems to have failed!"
+              }
+            }
+            sh 'sudo chmod 666 /tmp/test-stop2.log || true'
+            sh 'cp -f /tmp/test-stop2.log archives/deconnexion-test || true'
+            sh 'sudo rm -f /tmp/test-stop2.log || true'
+            stash allowEmpty: true, includes: 'archives/deconnexion-test/*.*', name: 'ue_logs_stop2'
           }
         }
       }
@@ -427,6 +502,9 @@ pipeline {
             unstash 'gNB_image'
             unstash 'gNB_logs'
             unstash 'ue_logs'
+            unstash 'ue_logs_start2'
+            unstash 'gNB_logs_after_first_stop'
+            unstash 'ue_logs_stop2'
           } catch (Exception e) {
             echo "could not retrieve stashes from gNB or UE server"
           }
