chore(ci): adding an out-of-coverage test
Signed-off-by: Raphael Defosseux <raphael.defosseux@eurecom.fr>

diff --git a/ci-scripts/Jenkinsfile-GitLab-COTS-UE-Test b/ci-scripts/Jenkinsfile-GitLab-COTS-UE-Test
--- a/ci-scripts/Jenkinsfile-GitLab-COTS-UE-Test
+++ b/ci-scripts/Jenkinsfile-GitLab-COTS-UE-Test
@@ -227,6 +227,7 @@ pipeline {
               sh "sudo rm -f /tmp/oai-gnb-l2-trace.pcap /tmp/oai-gnb-l2-trace.logs"
               sh 'nohup sudo tshark -i any -f "sctp or udp port 9999" -w /tmp/oai-gnb-l2-trace.pcap > /tmp/oai-gnb-l2-trace.logs 2>&1 &'
               sleep 2
+              sh 'sudo ./ci-scripts/control-attenuators.py --set-attenuation 0 || true'
               // Deploying now
               dir ('ci-scripts/docker-compose/gnb-ci-testbed') {
                 sh "sudo b2xx_fx3_utils --reset-device"
@@ -368,6 +369,7 @@ pipeline {
               sh "sudo rm -f /tmp/oai-gnb-l2-trace.pcap /tmp/oai-gnb-l2-trace.logs"
               sh 'nohup sudo tshark -i any -f "sctp or udp port 9999" -w /tmp/oai-gnb-l2-trace.pcap > /tmp/oai-gnb-l2-trace.logs 2>&1 &'
               sleep 2
+              sh 'sudo ./ci-scripts/control-attenuators.py --set-attenuation 0 || true'
               // Deploying now
               dir ('ci-scripts/docker-compose/gnb-ci-testbed') {
                 sh "sudo b2xx_fx3_utils --reset-device"
@@ -452,6 +454,7 @@ pipeline {
                 sh "sudo chmod 666 /tmp/oai-gnb-l2-trace.* || true"
                 sh "cp /tmp/oai-gnb-l2-trace.* archives/deconnection-test-stop0 || true"
                 sh "sudo rm -f /tmp/oai-gnb-l2-trace.*"
+                sh 'sudo ./ci-scripts/control-attenuators.py --set-attenuation 0 || true'
                 dir ('ci-scripts/docker-compose/gnb-ci-testbed') {
                   ranFullImage = fixFullRanImageTag(params.FULL_RAN_TAG)
                   sh "sed -i -e 's@image: oaisoftwarealliance/oai-gnb:develop@image: ${ranFullImage}@' docker-compose.yml"
@@ -522,6 +525,170 @@ pipeline {
                   sh "docker-compose down -t 3 || true"
                 }
                 stash allowEmpty: true, includes: 'archives/deconnection-test/*.*', name: 'deconnection_gNB_logs'
+                deployedGNB = false
+                if (ranFullImage.contains('porcepix')) {
+                  sh "docker rmi ${ranFullImage} || true"
+                }
+              }
+            }
+          }
+        }
+      }
+    }
+    stage ('Out-Of-Coverage Test') {
+      stages {
+        stage ('Deploy gNB #2') {
+          agent { label gnb_server }
+          steps {
+            script {
+              echo '\u2705 \u001B[32mDeploy gNB\u001B[0m'
+              ranFullImage = fixFullRanImageTag(params.FULL_RAN_TAG)
+              checkAndPullRanImage(ranFullImage)
+              sh 'mkdir -p archives/out-of-coverage-test'
+              // Adding capture on SCTP and L2 port 9999
+              sh "sudo rm -f /tmp/oai-gnb-l2-trace.pcap /tmp/oai-gnb-l2-trace.logs"
+              sh 'nohup sudo tshark -i any -f "sctp or udp port 9999" -w /tmp/oai-gnb-l2-trace.pcap > /tmp/oai-gnb-l2-trace.logs 2>&1 &'
+              sleep 2
+              sh 'sudo ./ci-scripts/control-attenuators.py --set-attenuation 0 || true'
+              // Deploying now
+              dir ('ci-scripts/docker-compose/gnb-ci-testbed') {
+                sh "sudo b2xx_fx3_utils --reset-device"
+                sh "sudo uhd_find_devices > /dev/null 2>&1 || true"
+                sleep 5
+                sh "sed -i -e 's@image: oaisoftwarealliance/oai-gnb:develop@image: ${ranFullImage}@' docker-compose.yml"
+                sh "docker-compose up -d"
+                deployedGNB = true
+                gNBStatus = checkStatusOnGNB()
+                if (gNBStatus > 0) {
+                  error ("gNB did NOT deploy properly")
+                }
+              }
+            }
+          }
+          post {
+            success {
+              script {
+                gnbDeploy    = true
+              }
+            }
+            unsuccessful {
+              script {
+                sh "sudo pkill tshark || true"
+                sleep 2
+                sh "sudo chmod 666 /tmp/oai-gnb-l2-trace.* || true"
+                sh "cp /tmp/oai-gnb-l2-trace.* archives/out-of-coverage-test || true"
+                sh "sudo rm -f /tmp/oai-gnb-l2-trace.*"
+                dir ('ci-scripts/docker-compose/gnb-ci-testbed') {
+                  sh "docker-compose stop -t 3 || true"
+                  sleep 2
+                  sh "docker logs sa-b210-gnb > ../../../archives/out-of-coverage-test/oai-gnb.logs 2>&1 || true"
+                  sh "docker-compose down -t 3 || true"
+                }
+                stash allowEmpty: true, includes: 'archives/out-of-coverage-test/*.*', name: 'out_of_coverage_gNB_logs'
+                deployedGNB  = false
+                gnbDeploy    = false
+                if (ranFullImage.contains('porcepix')) {
+                  sh "docker rmi ${ranFullImage} || true"
+                }
+              }
+            }
+          }
+        }
+        stage ('Attach UE #2') {
+          agent { label ue_ctl_server }
+          steps {
+            lock(ue_ctl_resource) {
+              script {
+                echo '\u2705 \u001B[32mTesting the Out-Of-Coverage - Attach UE\u001B[0m'
+                sh 'mkdir -p archives/out-of-coverage-test'
+                dir ('ci-scripts/cots-ue-mbim-scripts') {
+                  // I don't want that stage to fail.
+                  // It's easier then to un-deploy gNB.
+                  try {
+                    sh 'sudo bash -c "set -o pipefail && ./start.sh 2>&1 | tee /tmp/test-start4.log"'
+                  } catch (Exception e) {
+                    echo "Test-Start #4 seems to have failed!"
+                  }
+                }
+                sh 'sudo chmod 666 /tmp/test-start4.log || true'
+                sh 'cp -f /tmp/test-start4.log archives/out-of-coverage-test || true'
+                sh 'sudo rm -f /tmp/test-start4.log || true'
+                stash allowEmpty: true, includes: 'archives/out-of-coverage-test/*.*', name: 'out_of_coverage_ue_logs_start'
+                // starting a background ping
+                sh 'nohup ping -I wwan0 -c 120 8.8.8.8 > /tmp/bk_ping.log 2>&1 &'
+              }
+            }
+          }
+        }
+        stage ('Attenuation out and in coverage') {
+          agent { label gnb_server }
+          steps {
+            script {
+              echo '\u2705 \u001B[32mTesting the Out-Of-Coverage - Making the UE out of coverage\u001B[0m'
+              sh 'mkdir -p archives/out-of-coverage'
+              sh 'sudo ./ci-scripts/control-attenuators.py --set-attenuation 0 || true'
+              // Normally the RSRP is around -109 dB
+              // Let's go quickly to -121 dB first
+              sh 'sudo ./ci-scripts/control-attenuators.py --range 12 --delay 24 2>&1 | tee archives/out-of-coverage/attenuation-control.log'
+              // Then slowly to -125 dB
+              sh 'sudo ./ci-scripts/control-attenuators.py --range 5 --delay 25 2>&1 | tee -a archives/out-of-coverage/attenuation-control.log'
+              sleep 5
+              // Back up to -121 dB slowly
+              sh 'sudo ./ci-scripts/control-attenuators.py --range -5 --delay 25 2>&1 | tee -a archives/out-of-coverage/attenuation-control.log'
+              sleep 5
+              // And back quickly to -109 dB
+              sh 'sudo ./ci-scripts/control-attenuators.py --range -12 --delay 24 2>&1 | tee -a archives/out-of-coverage/attenuation-control.log'
+            }
+          }
+        }
+        stage ('Check Re-Attachement of UE out of coverage') {
+          agent { label ue_ctl_server }
+          steps {
+            lock(ue_ctl_resource) {
+              script {
+                echo '\u2705 \u001B[32mTesting the Out-Of-Coverage - Check Re-Attachement of UE\u001B[0m'
+                sh 'mkdir -p archives/out-of-coverage-test'
+                dir ('ci-scripts/cots-ue-mbim-scripts') {
+                  sleep 60
+                  // I don't want that stage to fail.
+                  // It's easier then to un-deploy gNB.
+                  sh 'ping -I wwan0 -c 4 8.8.8.8 2>&1 | tee ../../archives/out-of-coverage-test/test-start5.log'
+                  sh 'ping -I wwan0.1 -c 4 8.8.8.8 2>&1 | tee -a ../../archives/out-of-coverage-test/test-start5.log'
+                  try {
+                    sh 'sudo bash -c "set -o pipefail && ./stop.sh 2>&1 | tee /tmp/test-stop4.log"'
+                  } catch (Exception e) {
+                    echo "Test-Stop #4 seems to have failed!"
+                  }
+                }
+                sh 'sudo chmod 666 /tmp/test-stop4.log || true'
+                sh 'cp -f /tmp/test-stop4.log archives/out-of-coverage-test || true'
+                sh 'sudo rm -f /tmp/test-stop4.log || true'
+                stash allowEmpty: true, includes: 'archives/out-of-coverage-test/*.*', name: 'out_of_coverage_ue_logs'
+              }
+            }
+          }
+        }
+        stage ('Undeploy gNB #2') {
+          agent { label gnb_server }
+          steps {
+            script {
+              echo '\u2705 \u001B[32mUndeploy gNB\u001B[0m'
+              if (deployedGNB) {
+                sh 'mkdir -p archives/out_of_coverage-test'
+                sh "sudo pkill tshark || true"
+                sleep 2
+                sh "sudo chmod 666 /tmp/oai-gnb-l2-trace.* || true"
+                sh "cp /tmp/oai-gnb-l2-trace.* archives/out_of_coverage-test || true"
+                sh "sudo rm -f /tmp/oai-gnb-l2-trace.*"
+                dir ('ci-scripts/docker-compose/gnb-ci-testbed') {
+                  ranFullImage = fixFullRanImageTag(params.FULL_RAN_TAG)
+                  sh "sed -i -e 's@image: oaisoftwarealliance/oai-gnb:develop@image: ${ranFullImage}@' docker-compose.yml"
+                  sh "docker-compose stop -t 3 || true"
+                  sleep 2
+                  sh "docker logs sa-b210-gnb > ../../../archives/out_of_coverage-test/oai-gnb.logs 2>&1 || true"
+                  sh "docker-compose down -t 3 || true"
+                }
+                stash allowEmpty: true, includes: 'archives/out_of_coverage-test/*.*', name: 'out_of_coverage_gNB_logs'
                 deployedGNB = false
                 if (ranFullImage.contains('porcepix')) {
                   sh "docker rmi ${ranFullImage} || true"
